# -*- coding: utf-8 -*-
#!/usr/bin/python2

# Copyright 2014-2018 Payet Guillaume
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3, as published
# by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY, or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(910, 780)
        MainWindow.setMaximumSize(QtCore.QSize(910, 780))
        
        self.centralwidget = QtGui.QWidget()
        self.centralwidget.setStyleSheet(_fromUtf8(""))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.title = QtGui.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(305,5,300,80))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName(_fromUtf8("title"))
        self.versionLabel = QtGui.QLabel(self.centralwidget)
        self.versionLabel.setGeometry(QtCore.QRect(395, 85, 140, 30))
        self.versionLabel.setObjectName(_fromUtf8("about"))
        font.setPointSize(14)
        self.versionLabel.setFont(font)
        self.checkVersion = QtGui.QLabel(self.centralwidget)
        self.checkVersion.setGeometry(QtCore.QRect(305, 115, 300, 30))
        self.checkVersion.setObjectName(_fromUtf8("versionCheck"))
        font.setPointSize(10)
        self.checkVersion.setFont(font)
        self.checkVersion.setAlignment(QtCore.Qt.AlignHCenter| QtCore.Qt.AlignVCenter)

	self.groupBoxSettingsLeft = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxSettingsLeft.setGeometry(QtCore.QRect(5, 5, 298,138 ))
        self.groupBoxSettingsLeft.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid black;\n"
	"border-radius: 10px;\n"
	"}"))
        self.groupBoxSettingsLeft.setTitle(_fromUtf8(""))
        self.groupBoxSettingsLeft.setObjectName(_fromUtf8("groupBoxSettingsLeft"))
        self.groupBoxProfile = QtGui.QGroupBox(self.groupBoxSettingsLeft)
        self.groupBoxProfile.setGeometry(QtCore.QRect(3,3, 190,65 ))
        self.groupBoxProfile.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid SlateGrey;\n"
	"border-radius: 10px;\n"
	"}"))
	self.groupBoxProfile.setTitle(_fromUtf8(""))
        self.groupBoxProfile.setObjectName(_fromUtf8("groupBoxProfile"))
        self.buttonLoadProfile = QtGui.QPushButton(self.groupBoxProfile)
        self.buttonLoadProfile.setGeometry(QtCore.QRect(4,20, 90, 40))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(40)
        self.buttonLoadProfile.setFont(font)
        self.buttonLoadProfile.setAutoDefault(False)
        self.buttonLoadProfile.setDefault(False)
        self.buttonLoadProfile.setFlat(False)
        self.buttonLoadProfile.setObjectName(_fromUtf8("buttonLoadProfile"))
        self.buttonSaveProfile = QtGui.QPushButton(self.groupBoxProfile)
        self.buttonSaveProfile.setGeometry(QtCore.QRect(96,20, 90, 40))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(40)
        self.buttonSaveProfile.setFont(font)
        self.buttonSaveProfile.setAutoDefault(False)
        self.buttonSaveProfile.setDefault(False)
        self.buttonSaveProfile.setFlat(False)
        self.buttonSaveProfile.setObjectName(_fromUtf8("buttonLoadProfile"))
        self.labelProfile = QtGui.QLabel(self.groupBoxProfile)
        self.labelProfile.setGeometry(QtCore.QRect(70, 2, 60, 20))
        self.labelProfile.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProfile.setObjectName(_fromUtf8("LabelProfil"))
        font.setPointSize(12)
        self.labelProfile.setFont(font)
	self.groupBoxMonitor = QtGui.QGroupBox(self.groupBoxSettingsLeft)
        self.groupBoxMonitor.setGeometry(QtCore.QRect(3, 70, 190,65 ))
        self.groupBoxMonitor.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid SlateGrey;\n"
	"border-radius: 10px;\n"
	"}"))
        self.groupBoxMonitor.setTitle(_fromUtf8(""))
        self.groupBoxMonitor.setObjectName(_fromUtf8("groupBoxMonitor"))
        self.buttonStartMonitor = QtGui.QPushButton(self.groupBoxMonitor)
        self.buttonStartMonitor.setGeometry(QtCore.QRect(4,20, 90, 40))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(40)
        self.buttonStartMonitor.setFont(font)
        self.buttonStartMonitor.setAutoDefault(False)
        self.buttonStartMonitor.setDefault(False)
        self.buttonStartMonitor.setFlat(False)
        self.buttonStartMonitor.setObjectName(_fromUtf8("buttonStartMonitor"))
        self.buttonConfigureMonitor = QtGui.QPushButton(self.groupBoxMonitor)
        self.buttonConfigureMonitor.setGeometry(QtCore.QRect(96, 20, 90, 40))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(40)
        self.buttonConfigureMonitor.setFont(font)
        self.buttonConfigureMonitor.setAutoDefault(False)
        self.buttonConfigureMonitor.setDefault(False)
        self.buttonConfigureMonitor.setFlat(False)
        self.buttonConfigureMonitor.setEnabled(True)
        self.buttonConfigureMonitor.setObjectName(_fromUtf8("ButtonConfigureProfile"))
        self.labelMonitor = QtGui.QLabel(self.groupBoxMonitor)
        self.labelMonitor.setGeometry(QtCore.QRect(50, 2, 100, 20))
        self.labelMonitor.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMonitor.setObjectName(_fromUtf8("labelMonitor"))
        font.setPointSize(12)
        self.labelMonitor.setFont(font)
        self.groupBoxOvervolt = QtGui.QGroupBox(self.groupBoxSettingsLeft)
        self.groupBoxOvervolt.setGeometry(QtCore.QRect(194, 3, 100,132 ))
        self.groupBoxOvervolt.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid SlateGrey;\n"
	"border-radius: 10px;\n"
	"}"))
        self.groupBoxOvervolt.setTitle(_fromUtf8(""))
        self.groupBoxOvervolt.setObjectName(_fromUtf8("groupBoxOvervolt"))
        self.groupBoxOvervolt.setVisible(True)
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(40)
        self.labelTitleOvervolt = QtGui.QLabel(self.groupBoxOvervolt)
        self.labelTitleOvervolt.setGeometry(QtCore.QRect(10, 2, 80, 20))
        self.labelTitleOvervolt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitleOvervolt.setObjectName(_fromUtf8("labelTitleOvervolt"))
        self.labelTitleOvervolt.setFont(font)
	self.labelValueOvervolt = QtGui.QLabel(self.groupBoxOvervolt)
        self.labelValueOvervolt.setGeometry(QtCore.QRect(10, 25, 80, 20))
        self.labelValueOvervolt.setAlignment(QtCore.Qt.AlignCenter)
        self.labelValueOvervolt.setObjectName(_fromUtf8("labelValueOvervolt"))
        self.labelValueOvervolt.setFont(font)
        self.spinBoxOvervolt = QtGui.QSpinBox(self.groupBoxOvervolt)
        self.spinBoxOvervolt.setGeometry(QtCore.QRect(15, 55, 75, 25))
        self.spinBoxOvervolt.setAccelerated(True)
        self.spinBoxOvervolt.setPrefix("")
        self.spinBoxOvervolt.setMinimum(0)
        self.spinBoxOvervolt.setMaximum(0)
        self.spinBoxOvervolt.setValue(0)
        self.spinBoxOvervolt.setObjectName(_fromUtf8("spinBoxOvervolt"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(40)
        self.buttonOvervolt = QtGui.QPushButton(self.groupBoxOvervolt)
        self.buttonOvervolt.setGeometry(QtCore.QRect(5, 86, 90, 40))
        self.buttonOvervolt.setFont(font)
        self.buttonOvervolt.setAutoDefault(False)
        self.buttonOvervolt.setDefault(False)
        self.buttonOvervolt.setFlat(False)
        self.buttonOvervolt.setObjectName(_fromUtf8("ButtonConfigureProfile"))
        
        self.groupBoxSettingsRight = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxSettingsRight.setGeometry(QtCore.QRect(605, 5, 300,138 ))
        self.groupBoxSettingsRight.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid black;\n"
	"border-radius: 10px;\n"
	"}"))
        self.groupBoxSettingsRight.setTitle(_fromUtf8(""))
        self.groupBoxSettingsRight.setObjectName(_fromUtf8("groupBoxSettingsRight"))
        self.buttonAbout = QtGui.QPushButton(self.groupBoxSettingsRight)
        self.buttonAbout.setGeometry(QtCore.QRect(5, 5, 145, 62))
        self.buttonAbout.setAutoDefault(False)
        self.buttonAbout.setDefault(False)
        self.buttonAbout.setFlat(False)
        self.buttonAbout.setObjectName(_fromUtf8("buttonAbout"))
        # ~ self.buttonAbout.setIcon(QtGui.QIcon("/usr/share/nvidiux/img/i.png"))
        self.buttonDonate = QtGui.QPushButton(self.groupBoxSettingsRight)
        self.buttonDonate.setGeometry(QtCore.QRect(150, 5, 145, 62))
        self.buttonDonate.setAutoDefault(False)
        self.buttonDonate.setDefault(False)
        self.buttonDonate.setFlat(False)
        self.buttonDonate.setObjectName(_fromUtf8("buttonDonate"))
        self.buttonConfigure = QtGui.QPushButton(self.groupBoxSettingsRight)
        self.buttonConfigure.setGeometry(QtCore.QRect(5, 70, 145, 62))
        self.buttonConfigure.setAutoDefault(False)
        self.buttonConfigure.setDefault(False)
        self.buttonConfigure.setFlat(False)
        self.buttonConfigure.setObjectName(_fromUtf8("buttonConfigure"))
        # ~ self.buttonConfigure.setIcon(QtGui.QIcon("/usr/share/nvidiux/img/conf.png"))
        # ~ self.buttonConfigure.setIconSize(QtCore.QSize(16,16))
        self.buttonWeb = QtGui.QPushButton(self.groupBoxSettingsRight)
        self.buttonWeb.setGeometry(QtCore.QRect(150, 70, 145, 62))
        self.buttonWeb.setAutoDefault(False)
        self.buttonWeb.setDefault(False)
        self.buttonWeb.setFlat(False)
        self.buttonWeb.setObjectName(_fromUtf8("buttonWeb"))
        
	self.groupBoxTitleGpu = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxTitleGpu.setGeometry(QtCore.QRect(5, 150, 900,200 ))
        self.groupBoxTitleGpu.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid red;\n"
	"border-radius: 10px;\n"
	"}"))
        self.groupBoxTitleGpu.setTitle(_fromUtf8(""))
        self.groupBoxTitleGpu.setObjectName(_fromUtf8("groupBoxTitleGpu"))
        # ~ self.listWidgetGpu = QtGui.QListWidget(self.groupBoxTitleGpu)
        # ~ self.listWidgetGpu.setGeometry(QtCore.QRect(10, 4, 240, 190))
        # ~ self.listWidgetGpu.setObjectName(_fromUtf8("listWidgetGpu"))
        self.label_Nvidiux = ClickQLabel(self.groupBoxTitleGpu)
        self.label_Nvidiux.setGeometry(QtCore.QRect(10, 2, 240, 190))
        self.label_Nvidiux.setObjectName(_fromUtf8("label_Img"))
        self.label_Img = ClickQLabel(self.groupBoxTitleGpu)
        self.label_Img.setGeometry(QtCore.QRect(640, 2, 240, 190))
        self.label_Img.setObjectName(_fromUtf8("label_Img"))
        self.nomGpu = QtGui.QLabel(self.groupBoxTitleGpu)
        self.nomGpu.setGeometry(QtCore.QRect(255,0, 390, 100))
        self.nomGpu.setAlignment(QtCore.Qt.AlignCenter)
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.nomGpu.setFont(font)
        self.nomGpu.setObjectName(_fromUtf8("nomGpu"))
        self.labelGpuArch = QtGui.QLabel(self.groupBoxTitleGpu)
        self.labelGpuArch.setGeometry(QtCore.QRect(255,30, 390, 100))
        self.labelGpuArch.setAlignment(QtCore.Qt.AlignCenter)
        self.labelGpuArch.setObjectName(_fromUtf8("labelGpuArch"))
        self.checkBoxVaapi = QtGui.QCheckBox(self.groupBoxTitleGpu)
        self.checkBoxVaapi.setGeometry(QtCore.QRect(305, 95, 80, 20))
        self.checkBoxVaapi.setCheckable(True)
        self.checkBoxVaapi.setObjectName(_fromUtf8("checkBoxVaapi"))
        self.checkBoxSli = QtGui.QCheckBox(self.groupBoxTitleGpu)
        self.checkBoxSli.setEnabled(False)
        self.checkBoxSli.setGeometry(QtCore.QRect(390, 95, 50, 20))
        self.checkBoxSli.setCheckable(True)
        self.checkBoxSli.setObjectName(_fromUtf8("checkBoxSli"))
        self.checkBoxVSync = QtGui.QCheckBox(self.groupBoxTitleGpu)
        self.checkBoxVSync.setEnabled(True)
        self.checkBoxVSync.setGeometry(QtCore.QRect(455, 95, 71, 20))
        self.checkBoxVSync.setCheckable(True)
        self.checkBoxVSync.setChecked(False)
        self.checkBoxVSync.setObjectName(_fromUtf8("checkBoxVSync"))
        self.checkBoxMPerf = QtGui.QCheckBox(self.groupBoxTitleGpu)
        self.checkBoxMPerf.setEnabled(True)
        self.checkBoxMPerf.setGeometry(QtCore.QRect(530, 95, 90, 20))
        self.checkBoxMPerf.setCheckable(True)
        self.checkBoxMPerf.setChecked(False)
        self.checkBoxMPerf.setObjectName(_fromUtf8("checkBoxMPerf"))
        self.checkBoxFan = QtGui.QCheckBox(self.groupBoxTitleGpu)
        self.checkBoxFan.setEnabled(True)
        self.checkBoxFan.setGeometry(QtCore.QRect(255,140, 20, 20))
        self.checkBoxFan.setCheckable(True)
        self.checkBoxFan.setChecked(False)
        self.checkBoxFan.setObjectName(_fromUtf8("checkBoxFan"))
        self.labelFan = QtGui.QLabel(self.groupBoxTitleGpu)
        self.labelFan.setGeometry(QtCore.QRect(285, 135, 120, 30))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelFan.setFont(font)
        self.labelFan.setObjectName(_fromUtf8("labelFan"))
        self.labelFanVitesse = QtGui.QLabel(self.groupBoxTitleGpu)
        self.labelFanVitesse.setGeometry(QtCore.QRect(500, 135, 125, 30))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelFanVitesse.setFont(font)
        self.labelFanVitesse.setObjectName(_fromUtf8("labelFanVitesse"))
        self.SliderFan = QtGui.QSlider(self.groupBoxTitleGpu)
        self.SliderFan.setEnabled(True)
        self.SliderFan.setGeometry(QtCore.QRect(250, 150, 400, 50))
        self.SliderFan.setAutoFillBackground(False)
        self.SliderFan.setStyleSheet(_fromUtf8("color: rgb(205, 0, 0);"))
        self.SliderFan.setSingleStep(2)
        self.SliderFan.setSliderPosition(0)
        self.SliderFan.setOrientation(QtCore.Qt.Horizontal)
        self.SliderFan.setTickInterval(2)
        self.SliderFan.setObjectName(_fromUtf8("SliderFan"))
        
        self.groupBoxOverclock = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxOverclock.setGeometry(QtCore.QRect(458, 355, 446,290))
        self.groupBoxOverclock.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid MediumBlue;\n"
	"border-radius: 10px;\n"
	"}"))
        self.groupBoxOverclock.setTitle(_fromUtf8(""))
        self.groupBoxOverclock.setObjectName(_fromUtf8("groupBoxOverclock"))
        self.VitesseGpu = QtGui.QLabel(self.groupBoxOverclock)
        self.VitesseGpu.setGeometry(QtCore.QRect(16, 10, 130, 50))
        font.setFamily(_fromUtf8("Liberation Serif"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VitesseGpu.setFont(font)
        self.VitesseGpu.setObjectName(_fromUtf8("VitesseGpu"))
        self.label_Dfreq_Gpu = QtGui.QLabel(self.groupBoxOverclock)
        self.label_Dfreq_Gpu.setGeometry(QtCore.QRect(180, 15, 150, 40))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Dfreq_Gpu.setFont(font)
        self.label_Dfreq_Gpu.setObjectName(_fromUtf8("label_Dfreq_Gpu"))
        self.lcdGPU = QtGui.QLCDNumber(self.groupBoxOverclock)
        self.lcdGPU.setGeometry(QtCore.QRect(300, 20, 60, 30))
        self.lcdGPU.setDigitCount(6)
        self.lcdGPU.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdGPU.setObjectName(_fromUtf8("lcdGPU"))
        self.labelMhzGpu = QtGui.QLabel(self.groupBoxOverclock)
        self.labelMhzGpu.setGeometry(QtCore.QRect(370, 15, 50, 40))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelMhzGpu.setFont(font)
        self.labelMhzGpu.setObjectName(_fromUtf8("labelMhzGpu"))
        self.SliderGpu = QtGui.QSlider(self.groupBoxOverclock)
        self.SliderGpu.setGeometry(QtCore.QRect(5, 35, 420, 50))
        self.SliderGpu.setStyleSheet(_fromUtf8("color: rgb(205, 0, 0);"))
        self.SliderGpu.setSingleStep(2)
        self.SliderGpu.setOrientation(QtCore.Qt.Horizontal)
        self.SliderGpu.setObjectName(_fromUtf8("SliderGpu"))
        self.VitesseShader = QtGui.QLabel(self.groupBoxOverclock)
        self.VitesseShader.setGeometry(QtCore.QRect(16, 85, 130, 50))
        font.setFamily(_fromUtf8("Liberation Serif"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.VitesseShader.setFont(font)
        self.VitesseShader.setObjectName(_fromUtf8("VitesseShader"))
        self.label_Dfreq_Shader = QtGui.QLabel(self.groupBoxOverclock)
        self.label_Dfreq_Shader.setGeometry(QtCore.QRect(180, 90, 150, 40))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Dfreq_Shader.setFont(font)
        self.label_Dfreq_Shader.setObjectName(_fromUtf8("label_Dfreq_Shader"))
        self.lcdShader = QtGui.QLCDNumber(self.groupBoxOverclock)
        self.lcdShader.setGeometry(QtCore.QRect(300, 95, 60, 30))
        self.lcdShader.setDigitCount(6)
        self.lcdShader.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdShader.setProperty("intValue", 0)
        self.lcdShader.setObjectName(_fromUtf8("lcdShader"))
        self.labelMhzShader = QtGui.QLabel(self.groupBoxOverclock)
        self.labelMhzShader.setGeometry(QtCore.QRect(370, 90, 50, 40))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelMhzShader.setFont(font)
        self.labelMhzShader.setObjectName(_fromUtf8("labelMhzShader"))
        self.SliderShader = QtGui.QSlider(self.groupBoxOverclock)
        self.SliderShader.setEnabled(True)
        self.SliderShader.setGeometry(QtCore.QRect(5, 110, 420, 50))
        self.SliderShader.setAutoFillBackground(False)
        self.SliderShader.setStyleSheet(_fromUtf8("color: rgb(205, 0, 0);"))
        self.SliderShader.setSingleStep(2)
        self.SliderShader.setSliderPosition(0)
        self.SliderShader.setOrientation(QtCore.Qt.Horizontal)
        self.SliderShader.setTickInterval(2)
        self.SliderShader.setObjectName(_fromUtf8("SliderShader"))
        self.Memoire = QtGui.QLabel(self.groupBoxOverclock)
        self.Memoire.setGeometry(QtCore.QRect(16, 160, 130, 50))
        font.setFamily(_fromUtf8("Liberation Serif"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Memoire.setFont(font)
        self.Memoire.setObjectName(_fromUtf8("Memoire"))
        self.label_Dfreq_Mem = QtGui.QLabel(self.groupBoxOverclock)
        self.label_Dfreq_Mem.setGeometry(QtCore.QRect(180, 165, 150, 40))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Dfreq_Mem.setFont(font)
        self.label_Dfreq_Mem.setObjectName(_fromUtf8("label_Dfreq_Mem"))
        self.lcdMem = QtGui.QLCDNumber(self.groupBoxOverclock)
        self.lcdMem.setGeometry(QtCore.QRect(300, 170, 60, 30))
        self.lcdMem.setDigitCount(6)
        self.lcdMem.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdMem.setObjectName(_fromUtf8("lcdMem"))
        self.labelMhzMem = QtGui.QLabel(self.groupBoxOverclock)
        self.labelMhzMem.setGeometry(QtCore.QRect(370, 165, 50, 40))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelMhzMem.setFont(font)
        self.labelMhzMem.setObjectName(_fromUtf8("labelMhzMem")) 
        self.SliderMem = QtGui.QSlider(self.groupBoxOverclock)
        self.SliderMem.setGeometry(QtCore.QRect(5, 185, 420, 50))
        self.SliderMem.setStyleSheet(_fromUtf8("color: rgb(205, 0, 0);"))
        self.SliderMem.setSingleStep(2)
        self.SliderMem.setOrientation(QtCore.Qt.Horizontal)
        self.SliderMem.setObjectName(_fromUtf8("SliderMem"))
        self.buttonReset = QtGui.QPushButton(self.groupBoxOverclock)
        self.buttonReset.setGeometry(QtCore.QRect(35, 230, 180, 50))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buttonReset.setFont(font)
        self.buttonReset.setAutoDefault(False)
        self.buttonReset.setDefault(False)
        self.buttonReset.setFlat(False)
        self.buttonReset.setObjectName(_fromUtf8("buttonReset"))
        self.buttonApply = QtGui.QPushButton(self.groupBoxOverclock)
        self.buttonApply.setGeometry(QtCore.QRect(235, 230, 180, 50))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.buttonApply.setFont(font)
        self.buttonApply.setStyleSheet(_fromUtf8(""))
        self.buttonApply.setDefault(False)
        self.buttonApply.setObjectName(_fromUtf8("buttonApply"))
        
        self.groupBoxInfoGpu = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxInfoGpu.setGeometry(QtCore.QRect(5, 355, 446,290))
        self.groupBoxInfoGpu.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid MediumBlue;\n"
	"border-radius: 10px;\n"
	"}"))
        self.groupBoxInfoGpu.setTitle(_fromUtf8(""))
        self.groupBoxInfoGpu.setObjectName(_fromUtf8("groupBoxInfoGpu"))
        self.buttonSwitchApi = QtGui.QPushButton(self.groupBoxInfoGpu)
        self.buttonSwitchApi.setGeometry(QtCore.QRect(360, 35, 25, 25))
        self.buttonSwitchApi.setAutoDefault(False)
        self.buttonSwitchApi.setDefault(False)
        self.buttonSwitchApi.setFlat(False)
        self.buttonSwitchApi.setObjectName(_fromUtf8("buttonSwitchApi"))
        self.buttonSwitchApi.setIcon(QtGui.QIcon("/usr/share/nvidiux/img/switch25.png"))
        self.PiloteVersion = QtGui.QLabel(self.groupBoxInfoGpu)
        self.PiloteVersion.setGeometry(QtCore.QRect(30, 25, 150, 45))
        self.PiloteVersion.setStyleSheet(_fromUtf8("border-color: rgb(0, 0, 0);"))
        self.PiloteVersion.setAlignment(QtCore.Qt.AlignCenter)
        self.PiloteVersion.setMargin(2)
        self.PiloteVersion.setObjectName(_fromUtf8("PiloteVersion"))
        self.OpenGlSupport = QtGui.QLabel(self.groupBoxInfoGpu)
        self.OpenGlSupport.setGeometry(QtCore.QRect(205, 25, 150, 45))
        self.OpenGlSupport.setAlignment(QtCore.Qt.AlignCenter)
        self.OpenGlSupport.setMargin(2)
        self.OpenGlSupport.setObjectName(_fromUtf8("OpenGlSupport"))
        self.UGPU = QtGui.QLabel(self.groupBoxInfoGpu)
        self.UGPU.setGeometry(QtCore.QRect(205, 95, 150, 45))
        self.UGPU.setAlignment(QtCore.Qt.AlignCenter)
        self.UGPU.setMargin(2)
        self.UGPU.setObjectName(_fromUtf8("UGPU"))
        self.buttonSwitchUseGpu = QtGui.QPushButton(self.groupBoxInfoGpu)
        self.buttonSwitchUseGpu.setGeometry(QtCore.QRect(360, 105, 25, 25))
        self.buttonSwitchUseGpu.setAutoDefault(False)
        self.buttonSwitchUseGpu.setDefault(False)
        self.buttonSwitchUseGpu.setFlat(False)
        self.buttonSwitchUseGpu.setObjectName(_fromUtf8("buttonSwitchUseGpu"))
        self.buttonSwitchUseGpu.setIcon(QtGui.QIcon("/usr/share/nvidiux/img/switch25.png"))
        self.CudaCore = QtGui.QLabel(self.groupBoxInfoGpu)
        self.CudaCore.setGeometry(QtCore.QRect(30, 225, 150, 45))
        self.CudaCore.setAlignment(QtCore.Qt.AlignCenter)
        self.CudaCore.setMargin(2)
        self.CudaCore.setObjectName(_fromUtf8("CudaCore"))
        self.Temp = QtGui.QLabel(self.groupBoxInfoGpu)
        self.Temp.setGeometry(QtCore.QRect(30, 95, 150, 45))
        self.Temp.setAlignment(QtCore.Qt.AlignCenter)
        self.Temp.setMargin(2)
        self.Temp.setObjectName(_fromUtf8("Temp"))
        self.UMem = QtGui.QLabel(self.groupBoxInfoGpu)
        self.UMem.setGeometry(QtCore.QRect(205, 155, 150, 45))
        self.UMem.setAlignment(QtCore.Qt.AlignCenter)
        self.UMem.setMargin(2)
        self.UMem.setObjectName(_fromUtf8("UMem"))
        self.buttonSwitchUseMem = QtGui.QPushButton(self.groupBoxInfoGpu)
        self.buttonSwitchUseMem.setGeometry(QtCore.QRect(360, 165, 25, 25))
        self.buttonSwitchUseMem.setAutoDefault(False)
        self.buttonSwitchUseMem.setDefault(False)
        self.buttonSwitchUseMem.setFlat(False)
        self.buttonSwitchUseMem.setObjectName(_fromUtf8("buttonSwitchUseMem"))
        self.buttonSwitchUseMem.setIcon(QtGui.QIcon("/usr/share/nvidiux/img/switch25.png"))
        self.UPCIE = QtGui.QLabel(self.groupBoxInfoGpu)
        self.UPCIE.setGeometry(QtCore.QRect(30, 155, 150, 45))
        self.UPCIE.setAlignment(QtCore.Qt.AlignCenter)
        self.UPCIE.setMargin(2)
        self.UPCIE.setObjectName(_fromUtf8("UPCIE"))
        self.MemGpu = QtGui.QLabel(self.groupBoxInfoGpu)
        self.MemGpu.setGeometry(QtCore.QRect(205, 225, 150, 45))
        self.MemGpu.setAlignment(QtCore.Qt.AlignCenter)
        self.MemGpu.setMargin(2)
        self.MemGpu.setObjectName(_fromUtf8("MemGpu"))
        self.buttonSwitchTypeMem = QtGui.QPushButton(self.groupBoxInfoGpu)
        self.buttonSwitchTypeMem.setGeometry(QtCore.QRect(360, 235, 25, 25))
        self.buttonSwitchTypeMem.setAutoDefault(False)
        self.buttonSwitchTypeMem.setDefault(False)
        self.buttonSwitchTypeMem.setFlat(False)
        self.buttonSwitchTypeMem.setObjectName(_fromUtf8("buttonSwitchTypeMem"))
        self.buttonSwitchTypeMem.setIcon(QtGui.QIcon("/usr/share/nvidiux/img/switch25.png"))

        self.groupBoxMessage = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxMessage.setGeometry(QtCore.QRect(5, 650, 900,140 ))
        self.groupBoxMessage.setStyleSheet(_fromUtf8("QGroupBox \n"
	"{ \n"
	"border: 2px solid black;\n"
	"border-radius: 10px;\n"
	"}"))
        self.groupBoxMessage.setTitle(_fromUtf8(""))
        self.groupBoxMessage.setObjectName(_fromUtf8("groupBoxMessage"))
        self.Message = QtGui.QLabel(self.groupBoxMessage)
        self.Message.setGeometry(QtCore.QRect(5, 5, 890,90))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Message.setFont(font)
        self.Message.setText(_fromUtf8(""))
        self.Message.setAlignment(QtCore.Qt.AlignCenter)
        self.Message.setObjectName(_fromUtf8("Message"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuMonitor = QtGui.QMenu(self.menubar)
        self.menuMonitor.setObjectName(_fromUtf8("menuMonitor"))
        MainWindow.setMenuBar(self.menubar)
        
        self.actionLoadProfile = QtGui.QAction(MainWindow)
        self.actionLoadProfile.setObjectName(_fromUtf8("actionLoadProfile"))
        self.actionSaveProfile = QtGui.QAction(MainWindow)
        self.actionSaveProfile.setObjectName(_fromUtf8("actionSaveProfile"))
        self.actionPref = QtGui.QAction(MainWindow)
        self.actionPref.setObjectName(_fromUtf8("actionPref"))
        self.actionQuitter = QtGui.QAction(MainWindow)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionStartMonitor = QtGui.QAction(MainWindow)
        self.actionStartMonitor.setObjectName(_fromUtf8("actionStartMonitor"))
        self.actionConfigureMonitor = QtGui.QAction(MainWindow)
        self.actionConfigureMonitor.setObjectName(_fromUtf8("actionConfigureMonitor"))
        
        self.menuFichier.addAction(self.actionLoadProfile)
        self.menuFichier.addAction(self.actionSaveProfile)
        self.menuFichier.addAction(self.actionPref)
        self.menuFichier.addAction(self.actionAbout)
        self.menuFichier.addAction(self.actionQuitter)
        self.menuMonitor.addAction(self.actionStartMonitor)
        self.menuMonitor.addAction(self.actionConfigureMonitor)
        
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuMonitor.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Nvidiux", None))
        self.Memoire.setText(_translate("MainWindow", "Memoire", None))
        self.VitesseShader.setText(_translate("MainWindow", "Shader", None))
        self.VitesseGpu.setText(_translate("MainWindow", "Gpu", None))
        self.title.setText(_translate("MainWindow", "Nvidiux", None))
        self.checkVersion.setText(_translate("MainWindow", "Nvidiux est a jour", None))
        self.buttonReset.setText(_translate("MainWindow", "Reset", None))
        self.buttonApply.setText(_translate("MainWindow", "Appliquer", None))
        self.labelFanVitesse.setText(_translate("MainWindow", "Auto",None))
        self.labelFan.setText(_translate("MainWindow", "Fan", None))
        self.buttonStartMonitor.setText(_translate("MainWindow", "Lancer", None))
        self.buttonConfigureMonitor.setText(_translate("MainWindow", "Configurer", None))
        self.buttonAbout.setText(_translate("MainWindow", "A Propos", None))
        self.buttonConfigure.setText(_translate("MainWindow", "Parametres", None))
        self.buttonWeb.setText(_translate("MainWindow", "Rapport", None))
        self.buttonDonate.setText(_translate("MainWindow", "Faire un don", None))
        self.labelTitleOvervolt.setText(_translate("MainWindow", "Volt", None))
        self.labelValueOvervolt.setText(_translate("MainWindow", "0 μv", None))
        self.buttonOvervolt.setText(_translate("MainWindow", "Changer", None))
        self.spinBoxOvervolt.setSuffix(_translate("MainWindow", " μv", None))
        self.labelMonitor.setText(_translate("MainWindow", "Moniteur", None))
        self.buttonLoadProfile.setText(_translate("MainWindow", "Charger", None))
        self.buttonSaveProfile.setText(_translate("MainWindow", "Enregister", None))
        self.labelProfile.setText(_translate("MainWindow", "Profil", None))
        self.labelMhzGpu.setText(_translate("MainWindow", "Mhz", None))
        self.labelMhzShader.setText(_translate("MainWindow", "Mhz", None))
        self.labelMhzMem.setText(_translate("MainWindow", "Mhz", None))
        self.checkBoxSli.setText(_translate("MainWindow", "Sli", None))
        self.checkBoxVaapi.setText(_translate("MainWindow", "Vaapi", None))
        self.checkBoxVSync.setText(_translate("MainWindow", "VSync", None))
        self.checkBoxMPerf.setText(_translate("MainWindow", "Max Perf", None))
        self.PiloteVersion.setText(_translate("MainWindow", "Version pilote", None))
        self.OpenGlSupport.setText(_translate("MainWindow", "OpenGl Support", None))
        self.MemGpu.setText(_translate("MainWindow", "Mem Gpu", None))
        self.CudaCore.setText(_translate("MainWindow", "Cudacore", None))
        self.UGPU.setText(_translate("MainWindow", "Gpu utilisation", None))
        self.UMem.setText(_translate("MainWindow", "Mem utilisation", None))
        self.UPCIE.setText(_translate("MainWindow", "Pcie utili", None))
        self.Temp.setText(_translate("MainWindow", "Temp", None))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier", None))
        self.menuMonitor.setTitle(_translate("MainWindow", "Moniteur", None))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter", None))
        self.actionStartMonitor.setText(_translate("MainWindow", "Start", None))
        self.actionConfigureMonitor.setText(_translate("MainWindow", "Configurer", None))
        self.actionAbout.setText(_translate("MainWindow", "A Propos", None))
        self.actionPref.setText(_translate("MainWindow", "Preferences", None))
        self.actionLoadProfile.setText(_translate("MainWindow", "Charger", None))
        self.actionSaveProfile.setText(_translate("MainWindow", "Enregistrer", None))

class ClickQLabel(QtGui.QLabel):
 
    def __init(self, parent):
        QLabel.__init__(self, parent)
 
    def mouseReleaseEvent(self, ev):
        self.emit(QtCore.SIGNAL('clicked()'))
